image: node:20-alpine

stages:
  - build
  - publish
  - review
  - staging
  - production
  - cleanup

variables:
  DOCKER_IMAGE_NAME_FE: "$HARBOR_URL/xrosinec/dareg-ui"
  DOCKER_IMAGE_NAME_BE: "$HARBOR_URL/xrosinec/dareg-server"
  CLUSTER_DOMAIN: "dyn.cloud.e-infra.cz"
  DEPLOYMENT_TLD: dareg.${CLUSTER_DOMAIN}
  K8S_AGENT_NAME: agent-dareg
  K8S_NAMESPACE: ceitec-dareg-ns

cache:
  key:
    files:
      - package.json
  paths:
    - $CI_PROJECT_DIR/.npm/
    - $CI_PROJECT_DIR/node_modules

# unit test:
#     stage: test
#     before_script:
#       - npm ci --cache .npm --prefer-offline
#     script:
#       - npm run test
#     needs: ["eslint"]

# eslint:
#     stage: lint
#     before_script:
#       - npm ci --cache .npm --prefer-offline
#     script:
#       - npm run lint

build_app:
  stage: build
  before_script:
    - npm i --cache .npm --prefer-offline
  script:
    - unset CI #This will need to be fixed + add test beforehand
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/
    expire_in: 2 hours
  # needs: ["unit test"]

build_image-fe:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $HUB_REGISTRY_USER -p $HARBOR_PASSWORD $HARBOR_URL
    - ls -la
  script:
    - docker build --tag $DOCKER_IMAGE_NAME_FE:$CI_COMMIT_SHORT_SHA -f $CI_PROJECT_DIR/Dockerfile .
    - docker push $DOCKER_IMAGE_NAME_FE:$CI_COMMIT_SHORT_SHA
  needs: ["build_app"]

build_image-be:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $HUB_REGISTRY_USER -p $HARBOR_PASSWORD $HARBOR_URL
    - ls -la
  script:
    - docker build --tag $DOCKER_IMAGE_NAME_BE:$CI_COMMIT_SHORT_SHA -f $CI_PROJECT_DIR/Dockerfile.server .
    - docker push $DOCKER_IMAGE_NAME_BE:$CI_COMMIT_SHORT_SHA
  # needs: ["build_app"]

.deploy: &deploy
  image:
    name: zhangsean/kubectl
    entrypoint: ['']
  before_script:
    - kubectl config use-context $(kubectl config get-contexts -o=name | grep ${K8S_AGENT_NAME})
  script:
    - mkdir $CI_PROJECT_DIR/manifests/prepared
    - cd $CI_PROJECT_DIR/manifests
    - for f in *.$APP_COMPONENT.yaml; do envsubst < $f > prepared/$f; done
    - ls -la prepared/ || true
    - cat prepared/*.yaml || true
    - kubectl apply -f prepared/ --recursive -n ${K8S_NAMESPACE}
  artifacts:
    name: deployments-$CI_COMMIT_REF_SLUG
    paths:
      - $CI_PROJECT_DIR/manifests/prepared/
    expire_in: 1 week

review:
  <<: *deploy
  stage: review
  variables:
    APP_COMPONENT: web
    APP: review-$CI_COMMIT_REF_SLUG
    APP_HOST: $CI_COMMIT_REF_SLUG.${DEPLOYMENT_TLD}
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.${DEPLOYMENT_TLD}
    on_stop: stop-review
  only:
    - branches
  except:
    - master

review-be:
  <<: *deploy
  stage: review
  variables:
    APP_COMPONENT: server
    APP: review-api-$CI_COMMIT_REF_SLUG
    APP_HOST: api.$CI_COMMIT_REF_SLUG.${DEPLOYMENT_TLD}
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://api.$CI_COMMIT_REF_SLUG.${DEPLOYMENT_TLD}
    on_stop: stop-review
  only:
    - branches
  except:
    - master

staging:
  <<: *deploy
  stage: staging
  variables:
    APP: staging
    APP_HOST: stage.${DEPLOYMENT_TLD}
  environment:
    name: staging
    url: https://stage.${DEPLOYMENT_TLD}
  only:
    - master

staging-be:
  <<: *deploy
  stage: staging
  variables:
    APP: staging-api
    APP_HOST: api.stage.${DEPLOYMENT_TLD}
  environment:
    name: staging
    url: https://api.stage.${DEPLOYMENT_TLD}
  only:
    - master

production:
  <<: *deploy
  stage: production
  variables:
    APP: production
    APP_HOST: ${DEPLOYMENT_TLD}
  when: manual
  environment:
    name: production
    url: https://${DEPLOYMENT_TLD}
  only:
    - master

production-be:
  <<: *deploy
  stage: production
  variables:
    APP: production-api
    APP_HOST: "api.${DEPLOYMENT_TLD}"
  when: manual
  environment:
    name: production
    url: "https://api.${DEPLOYMENT_TLD}"
  only:
    - master

stop-review:
  <<: *deploy
  stage: cleanup
  script:
    - echo "All cluster resources within the namespace ${K8S_NAMESPACE} with label 'deployment-id=$APP' will be removed" || true
    - kubectl delete deployments,services,ingresses,configmaps,secrets -n ${K8S_NAMESPACE} -l deployment-id=$APP
  when: manual
  variables:
    APP: review-$CI_COMMIT_REF_SLUG
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
