FROM node:20-alpine AS deps

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN apk add --no-cache git ca-certificates

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN pnpm build

FROM node:20-alpine AS runner

WORKDIR /app

RUN addgroup -g 1001 -S nodejs \
    && adduser -u 1001 -S -G nodejs nextjs

COPY --chown=nextjs:nodejs --from=builder /app/.next/standalone ./

COPY --chown=nextjs:nodejs --from=builder /app/public ./public
COPY --chown=nextjs:nodejs --from=builder /app/.next/static ./.next/static

EXPOSE 8081

RUN sed -i "s/process.env.HOSTNAME/'0.0.0.0'/g" server.js

USER nextjs

CMD ["node", "server.js"]
