services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    image: dareg-ui:local
    ports: ["5000:5000"]
    environment:
      PORT: 5000
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      NEXT_PUBLIC_AUTH_OIDC_ISSUER: ${NEXT_PUBLIC_AUTH_OIDC_ISSUER}
      NEXT_PUBLIC_AUTH_OIDC_CLIENT_ID: ${NEXT_PUBLIC_AUTH_OIDC_CLIENT_ID}
      NEXT_PUBLIC_APP_OIDC_METADATA_ISSUER: ${NEXT_PUBLIC_APP_OIDC_METADATA_ISSUER}
      NEXT_PUBLIC_APP_OIDC_METADATA_AUTHORIZATION_ENDPOINT: ${NEXT_PUBLIC_APP_OIDC_METADATA_AUTHORIZATION_ENDPOINT}
      NEXT_PUBLIC_APP_OIDC_METADATA_TOKEN_ENDPOINT: ${NEXT_PUBLIC_APP_OIDC_METADATA_TOKEN_ENDPOINT}
      NEXT_PUBLIC_APP_OIDC_METADATA_USERINFO_ENDPOINT: ${NEXT_PUBLIC_APP_OIDC_METADATA_USERINFO_ENDPOINT}
      NEXT_PUBLIC_APP_OIDC_SCOPE: ${NEXT_PUBLIC_APP_OIDC_SCOPE}
