FROM python:3.11-alpine

RUN adduser -D 1000 -u 1000

WORKDIR /app

RUN mkdir ./scheme && chown -R 1000:1000 ./scheme
RUN mkdir ./ui-scheme && chown -R 1000:1000 ./ui-scheme
RUN mkdir ./conf && chown -R 1000:1000 ./conf

COPY --chown=1000:1000 backend/requirements.txt backend/app.py backend/makedb.py ./

RUN pip install -r requirements.txt && python3 makedb.py

ENV FLASK_ENV production

EXPOSE 5000
USER 1000

CMD ["gunicorn", "-b", ":5000", "app:app"]