FROM python:3.11-alpine

RUN adduser -D 1000 -u 1000

WORKDIR /app

COPY --chown=1000:1000 backend/requirements.txt backend/app.py backend/makedb.py backend/init.sh ./

RUN pip install -r requirements.txt && chown 1000:1000 /app

ENV FLASK_ENV production

EXPOSE 5000

USER 1000

CMD ["/bin/sh", "-c", "./init.sh"]