FROM node:24-alpine AS deps

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN apk add --no-cache git ca-certificates

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

FROM node:24-alpine AS builder

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY --from=deps /app/node_modules ./node_modules

COPY . .

# Build-time environment variables
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_APP_VERSION
ARG NEXT_PUBLIC_APP_ENVIRONMENT
ARG NEXT_PUBLIC_API_URL

# Set environment variables for build
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION
ENV NEXT_PUBLIC_APP_ENVIRONMENT=$NEXT_PUBLIC_APP_ENVIRONMENT
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN pnpm build

FROM node:24-alpine AS runner

WORKDIR /app

RUN addgroup -g 1001 -S nodejs \
    && adduser -u 1001 -S -G nodejs nextjs

COPY --chown=nextjs:nodejs --from=builder /app/.next/standalone ./
COPY --chown=nextjs:nodejs --from=builder /app/public ./public
COPY --chown=nextjs:nodejs --from=builder /app/.next/static ./.next/static

# Copy startup script and fix line endings
COPY --chown=nextjs:nodejs startup.sh ./
RUN sed -i 's/\r$//' startup.sh && \
    chmod +x startup.sh && \
    ls -la startup.sh && \
    head -1 startup.sh

# Create .next directory with proper permissions for cache
RUN mkdir -p .next/cache && chown -R nextjs:nodejs .next

EXPOSE 5000

ENV HOSTNAME="0.0.0.0"

# Runtime environment variables with placeholders (will be replaced by startup script)
ENV NEXT_PUBLIC_AUTH_OIDC_CLIENT_ID="NEXT_PUBLIC_AUTH_OIDC_CLIENT_ID_PLACEHOLDER"
ENV NEXT_PUBLIC_AUTH_OIDC_ISSUER="NEXT_PUBLIC_AUTH_OIDC_ISSUER_PLACEHOLDER"
ENV NEXT_PUBLIC_APP_OIDC_METADATA_ISSUER="NEXT_PUBLIC_APP_OIDC_METADATA_ISSUER_PLACEHOLDER"
ENV NEXT_PUBLIC_APP_OIDC_METADATA_AUTHORIZATION_ENDPOINT="NEXT_PUBLIC_APP_OIDC_METADATA_AUTHORIZATION_ENDPOINT_PLACEHOLDER"
ENV NEXT_PUBLIC_APP_OIDC_METADATA_TOKEN_ENDPOINT="NEXT_PUBLIC_APP_OIDC_METADATA_TOKEN_ENDPOINT_PLACEHOLDER"
ENV NEXT_PUBLIC_APP_OIDC_METADATA_USERINFO_ENDPOINT="NEXT_PUBLIC_APP_OIDC_METADATA_USERINFO_ENDPOINT_PLACEHOLDER"
ENV NEXT_PUBLIC_APP_OIDC_SCOPE="NEXT_PUBLIC_APP_OIDC_SCOPE_PLACEHOLDER"
ENV NEXT_PUBLIC_APP_OIDC_METADATA_JWKS_URI="NEXT_PUBLIC_APP_OIDC_METADATA_JWKS_URI_PLACEHOLDER"
ENV NEXT_PUBLIC_APP_OIDC_METADATA_END_SESSION_ENDPOINT="NEXT_PUBLIC_APP_OIDC_METADATA_END_SESSION_ENDPOINT_PLACEHOLDER"
ENV APP_BASE_URL="APP_BASE_URL_PLACEHOLDER"
ENV APP_OIDC_REDIRECT_URL="APP_OIDC_REDIRECT_URL_PLACEHOLDER"
ENV APP_BASE_API_URL="APP_BASE_API_URL_PLACEHOLDER"
ENV APP_BASE_ONEZONE_URL="APP_BASE_ONEZONE_URL_PLACEHOLDER"
ENV APP_BASE_ONEZONE_PRETTY_URL="APP_BASE_ONEZONE_PRETTY_URL_PLACEHOLDER"
ENV PORT="PORT_PLACEHOLDER"
ENV APP_VERSION="APP_VERSION_PLACEHOLDER"
ENV APP_VERSION_DATE="APP_VERSION_DATE_PLACEHOLDER"
ENV APP_ENVIRONMENT="APP_ENVIRONMENT_PLACEHOLDER"
ENV NEXTAUTH_URL="NEXTAUTH_URL_PLACEHOLDER"
ENV AUTH_SECRET="AUTH_SECRET_PLACEHOLDER"
ENV SECRET="SECRET_PLACEHOLDER"
ENV AUTH_TRUST_HOST="AUTH_TRUST_HOST_PLACEHOLDER"

USER nextjs

# Debug: Show what's in the current directory
RUN ls -la

CMD ["/bin/sh", "-c", "ls -la && pwd && whoami && /bin/sh ./startup.sh"]
