// This file is auto-generated by @hey-api/openapi-ts

export const $BaseModel = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        created_by: {
            allOf: [
                {
                    '$ref': '#/components/schemas/UserSerializerMinimal'
                }
            ],
            readOnly: true
        }
    },
    required: ['created_by', 'id', 'name']
} as const;

export const $Dataset = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            maxLength: 500
        },
        metadata: {},
        onedata_file_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        onedata_share_id: {
            type: 'string',
            nullable: true,
            title: 'Onedata Default Share ID',
            maxLength: 512
        },
        onedata_dataset_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        onedata_space_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        doi: {
            type: 'string',
            nullable: true,
            maxLength: 50
        },
        reservationId: {
            type: 'string',
            nullable: true,
            title: 'Reservation ID',
            maxLength: 50
        },
        status: {
            '$ref': '#/components/schemas/Status464Enum'
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        project: {
            type: 'string',
            format: 'uuid'
        },
        schema: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        tags: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    },
    required: ['created', 'created_by', 'description', 'id', 'modified', 'modified_by', 'name', 'project']
} as const;

export const $DatasetResponse = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        created_by: {
            allOf: [
                {
                    '$ref': '#/components/schemas/UserSerializerMinimal'
                }
            ],
            readOnly: true
        },
        perms: {
            type: 'string',
            readOnly: true
        },
        shares: {
            type: 'string',
            readOnly: true
        },
        project: {
            allOf: [
                {
                    '$ref': '#/components/schemas/BaseModel'
                }
            ],
            readOnly: true
        },
        experiments: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Experiment'
            },
            readOnly: true
        },
        dataset_schema: {
            allOf: [
                {
                    '$ref': '#/components/schemas/BaseModel'
                }
            ],
            readOnly: true
        },
        modified_by: {
            allOf: [
                {
                    '$ref': '#/components/schemas/UserSerializerMinimal'
                }
            ],
            readOnly: true
        },
        onedata_visit_id: {
            type: 'string',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        description: {
            type: 'string',
            maxLength: 500
        },
        metadata: {},
        onedata_file_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        onedata_share_id: {
            type: 'string',
            nullable: true,
            title: 'Onedata Default Share ID',
            maxLength: 512
        },
        onedata_dataset_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        onedata_space_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        doi: {
            type: 'string',
            nullable: true,
            maxLength: 50
        },
        reservationId: {
            type: 'string',
            nullable: true,
            title: 'Reservation ID',
            maxLength: 50
        },
        status: {
            '$ref': '#/components/schemas/Status464Enum'
        },
        schema: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        tags: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    },
    required: ['created', 'created_by', 'dataset_schema', 'description', 'experiments', 'id', 'modified', 'modified_by', 'name', 'onedata_visit_id', 'perms', 'project', 'shares']
} as const;

export const $DefaultDataRowsEnum = {
    enum: [25, 50, 100, 250],
    type: 'integer',
    description: `* \`25\` - Value1
* \`50\` - Value2
* \`100\` - Value3
* \`250\` - Value4`
} as const;

export const $DefaultLangEnum = {
    enum: ['cs-CZ', 'en-US'],
    type: 'string',
    description: `* \`cs-CZ\` - Czech
* \`en-US\` - English`
} as const;

export const $DefaultThemeEnum = {
    enum: ['dark', 'light', 'system'],
    type: 'string',
    description: `* \`dark\` - Dark
* \`light\` - Light
* \`system\` - System`
} as const;

export const $Experiment = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        start_time: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        end_time: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        note: {
            type: 'string',
            maxLength: 500
        },
        status: {
            '$ref': '#/components/schemas/ExperimentStatusEnum'
        },
        onedata_file_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        dataset: {
            type: 'string',
            format: 'uuid'
        }
    },
    required: ['created', 'created_by', 'dataset', 'id', 'modified', 'modified_by']
} as const;

export const $ExperimentStatusEnum = {
    enum: ['new', 'prepared', 'running', 'synchronizing', 'success', 'failure', 'discarded'],
    type: 'string',
    description: `* \`new\` - NEW
* \`prepared\` - PREPARED
* \`running\` - RUNNING
* \`synchronizing\` - SYNCHRONIZING
* \`success\` - SUCCESS
* \`failure\` - FAILURE
* \`discarded\` - DISCARDED`
} as const;

export const $Facility = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        perms: {
            type: 'string',
            readOnly: true
        },
        shares: {
            type: 'string',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        abbreviation: {
            type: 'string',
            maxLength: 20
        },
        web: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 200
        },
        logo: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        },
        onedata_token: {
            type: 'string',
            title: 'Onedata Secret token',
            maxLength: 512
        },
        onedata_provider_url: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        }
    },
    required: ['abbreviation', 'created', 'created_by', 'id', 'modified', 'modified_by', 'name', 'perms', 'shares']
} as const;

export const $FacilitySerializerMinimal = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        abbreviation: {
            type: 'string',
            maxLength: 20
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 200
        },
        web: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        },
        logo: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        }
    },
    required: ['abbreviation', 'id', 'name']
} as const;

export const $Group = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 150
        }
    },
    required: ['name']
} as const;

export const $Instrument = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        support: {
            type: 'string',
            maxLength: 500
        },
        contact: {
            type: 'string',
            maxLength: 500
        },
        method: {
            type: 'string',
            maxLength: 500
        },
        facility: {
            allOf: [
                {
                    '$ref': '#/components/schemas/FacilitySerializerMinimal'
                }
            ],
            readOnly: true
        },
        default_data_dir: {
            type: 'string',
            title: 'Default data directory',
            maxLength: 1024
        }
    },
    required: ['contact', 'facility', 'id', 'method', 'name', 'support']
} as const;

export const $PaginatedDatasetResponseList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DatasetResponse'
            }
        }
    }
} as const;

export const $PaginatedExperimentList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Experiment'
            }
        }
    }
} as const;

export const $PaginatedFacilityList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Facility'
            }
        }
    }
} as const;

export const $PaginatedGroupList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Group'
            }
        }
    }
} as const;

export const $PaginatedInstrumentList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Instrument'
            }
        }
    }
} as const;

export const $PaginatedProfileList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Profile'
            }
        }
    }
} as const;

export const $PaginatedProjectResponseList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ProjectResponse'
            }
        }
    }
} as const;

export const $PaginatedSchemaList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Schema'
            }
        }
    }
} as const;

export const $PaginatedUserList = {
    type: 'object',
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/User'
            }
        }
    }
} as const;

export const $PatchedDataset = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            maxLength: 500
        },
        metadata: {},
        onedata_file_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        onedata_share_id: {
            type: 'string',
            nullable: true,
            title: 'Onedata Default Share ID',
            maxLength: 512
        },
        onedata_dataset_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        onedata_space_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        doi: {
            type: 'string',
            nullable: true,
            maxLength: 50
        },
        reservationId: {
            type: 'string',
            nullable: true,
            title: 'Reservation ID',
            maxLength: 50
        },
        status: {
            '$ref': '#/components/schemas/Status464Enum'
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        project: {
            type: 'string',
            format: 'uuid'
        },
        schema: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        tags: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const $PatchedExperiment = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        start_time: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        end_time: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        note: {
            type: 'string',
            maxLength: 500
        },
        status: {
            '$ref': '#/components/schemas/ExperimentStatusEnum'
        },
        onedata_file_id: {
            type: 'string',
            nullable: true,
            maxLength: 512
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        dataset: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const $PatchedFacility = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        perms: {
            type: 'string',
            readOnly: true
        },
        shares: {
            type: 'string',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        abbreviation: {
            type: 'string',
            maxLength: 20
        },
        web: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 200
        },
        logo: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        },
        onedata_token: {
            type: 'string',
            title: 'Onedata Secret token',
            maxLength: 512
        },
        onedata_provider_url: {
            type: 'string',
            format: 'uri',
            maxLength: 200
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        }
    }
} as const;

export const $PatchedGroup = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 150
        }
    }
} as const;

export const $PatchedInstrument = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        support: {
            type: 'string',
            maxLength: 500
        },
        contact: {
            type: 'string',
            maxLength: 500
        },
        method: {
            type: 'string',
            maxLength: 500
        },
        facility: {
            allOf: [
                {
                    '$ref': '#/components/schemas/FacilitySerializerMinimal'
                }
            ],
            readOnly: true
        },
        default_data_dir: {
            type: 'string',
            title: 'Default data directory',
            maxLength: 1024
        }
    }
} as const;

export const $PatchedProfile = {
    type: 'object',
    properties: {
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        default_data_rows: {
            allOf: [
                {
                    '$ref': '#/components/schemas/DefaultDataRowsEnum'
                }
            ],
            minimum: -2147483648,
            maximum: 2147483647
        },
        any_datasets: {
            type: 'string',
            readOnly: true
        },
        any_facilities: {
            type: 'string',
            readOnly: true
        },
        any_projects: {
            type: 'string',
            readOnly: true
        },
        app_version: {
            type: 'string',
            readOnly: true
        },
        avatar: {
            type: 'string',
            readOnly: true
        },
        last_login: {
            type: 'string',
            readOnly: true
        },
        default_theme: {
            '$ref': '#/components/schemas/DefaultThemeEnum'
        },
        default_lang: {
            '$ref': '#/components/schemas/DefaultLangEnum'
        }
    }
} as const;

export const $PatchedProject = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            maxLength: 500
        },
        onedata_space_id: {
            type: 'string',
            maxLength: 200
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        facility: {
            type: 'string',
            format: 'uuid'
        },
        default_dataset_schema: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    }
} as const;

export const $PatchedSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        version: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            default: 1
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            nullable: true,
            maxLength: 500
        },
        schema: {},
        uischema: {},
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        }
    }
} as const;

export const $PatchedUser = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            readOnly: true
        },
        username: {
            type: 'string',
            description: 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            pattern: '^[\\w.@+-]+$',
            maxLength: 150
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email address',
            maxLength: 254
        },
        groups: {
            type: 'array',
            items: {
                type: 'integer'
            },
            description: 'The groups this user belongs to. A user will get all permissions granted to each of their groups.'
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        name: {
            type: 'string',
            readOnly: true
        }
    }
} as const;

export const $Profile = {
    type: 'object',
    properties: {
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        default_data_rows: {
            allOf: [
                {
                    '$ref': '#/components/schemas/DefaultDataRowsEnum'
                }
            ],
            minimum: -2147483648,
            maximum: 2147483647
        },
        any_datasets: {
            type: 'string',
            readOnly: true
        },
        any_facilities: {
            type: 'string',
            readOnly: true
        },
        any_projects: {
            type: 'string',
            readOnly: true
        },
        app_version: {
            type: 'string',
            readOnly: true
        },
        avatar: {
            type: 'string',
            readOnly: true
        },
        last_login: {
            type: 'string',
            readOnly: true
        },
        default_theme: {
            '$ref': '#/components/schemas/DefaultThemeEnum'
        },
        default_lang: {
            '$ref': '#/components/schemas/DefaultLangEnum'
        }
    },
    required: ['any_datasets', 'any_facilities', 'any_projects', 'app_version', 'avatar', 'created', 'last_login']
} as const;

export const $Project = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            maxLength: 500
        },
        onedata_space_id: {
            type: 'string',
            maxLength: 200
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        facility: {
            type: 'string',
            format: 'uuid'
        },
        default_dataset_schema: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    required: ['created', 'created_by', 'description', 'facility', 'id', 'modified', 'modified_by', 'name']
} as const;

export const $ProjectResponse = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        created_by: {
            allOf: [
                {
                    '$ref': '#/components/schemas/UserSerializerMinimal'
                }
            ],
            readOnly: true
        },
        perms: {
            type: 'string',
            readOnly: true
        },
        shares: {
            type: 'string',
            readOnly: true
        },
        facility: {
            allOf: [
                {
                    '$ref': '#/components/schemas/FacilitySerializerMinimal'
                }
            ],
            readOnly: true
        },
        default_dataset_schema: {
            allOf: [
                {
                    '$ref': '#/components/schemas/BaseModel'
                }
            ],
            readOnly: true
        },
        project_schema: {
            allOf: [
                {
                    '$ref': '#/components/schemas/BaseModel'
                }
            ],
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        description: {
            type: 'string',
            maxLength: 500
        },
        onedata_space_id: {
            type: 'string',
            maxLength: 200
        },
        modified_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: ['created', 'created_by', 'default_dataset_schema', 'description', 'facility', 'id', 'modified', 'name', 'perms', 'project_schema', 'shares']
} as const;

export const $Reservation = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        from_date: {
            type: 'string',
            format: 'date-time'
        },
        to_date: {
            type: 'string',
            format: 'date-time'
        },
        user: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        project_id: {
            type: 'string'
        },
        dataset_status: {
            type: 'string',
            nullable: true,
            readOnly: true
        }
    },
    required: ['dataset_status', 'description', 'from_date', 'id', 'name', 'project_id', 'to_date', 'user']
} as const;

export const $Schema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        modified: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        version: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            default: 1
        },
        name: {
            type: 'string',
            maxLength: 200
        },
        description: {
            type: 'string',
            nullable: true,
            maxLength: 500
        },
        schema: {},
        uischema: {},
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        modified_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        }
    },
    required: ['created', 'created_by', 'id', 'modified', 'modified_by', 'name']
} as const;

export const $Status464Enum = {
    enum: ['new', 'finished'],
    type: 'string',
    description: `* \`new\` - NEW
* \`finished\` - FINISHED`
} as const;

export const $User = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            readOnly: true
        },
        username: {
            type: 'string',
            description: 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            pattern: '^[\\w.@+-]+$',
            maxLength: 150
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email address',
            maxLength: 254
        },
        groups: {
            type: 'array',
            items: {
                type: 'integer'
            },
            description: 'The groups this user belongs to. A user will get all permissions granted to each of their groups.'
        },
        first_name: {
            type: 'string',
            maxLength: 150
        },
        last_name: {
            type: 'string',
            maxLength: 150
        },
        name: {
            type: 'string',
            readOnly: true
        }
    },
    required: ['id', 'name', 'username']
} as const;

export const $UserSerializerMinimal = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            readOnly: true
        },
        full_name: {
            type: 'string',
            readOnly: true
        }
    },
    required: ['full_name', 'id']
} as const;