// This file is auto-generated by @hey-api/openapi-ts

import { SharesList } from "@/types/global";

export type BaseModel = {
    name: string;
    id: string;
    readonly created_by: UserSerializerMinimal;
};

export type Dataset = {
    readonly id: string;
    readonly created: string;
    readonly modified: string;
    name: string;
    description: string;
    metadata?: unknown;
    onedata_file_id?: string | null;
    onedata_share_id?: string | null;
    onedata_dataset_id?: string | null;
    onedata_space_id?: string | null;
    doi?: string | null;
    reservationId?: string | null;
    status?: Status464Enum;
    readonly created_by: number | null;
    readonly modified_by: number | null;
    project: string;
    schema?: string | null;
    tags?: Array<(string)>;
};

export type DatasetResponse = {
    id: string;
    name: string;
    readonly created_by: UserSerializerMinimal;
    readonly perms: string;
    readonly shares: SharesList;
    readonly project: BaseModel;
    readonly experiments: Array<Experiment>;
    readonly dataset_schema: BaseModel;
    readonly modified_by: UserSerializerMinimal;
    readonly onedata_visit_id: string;
    readonly created: string;
    readonly modified: string;
    description: string;
    metadata?: unknown;
    onedata_file_id?: string | null;
    onedata_share_id?: string | null;
    onedata_dataset_id?: string | null;
    onedata_space_id?: string | null;
    doi?: string | null;
    reservationId?: string | null;
    status?: Status464Enum;
    schema?: string | null;
    tags?: Array<(string)>;
};

/**
 * * `25` - Value1
 * * `50` - Value2
 * * `100` - Value3
 * * `250` - Value4
 */
export type DefaultDataRowsEnum = 25 | 50 | 100 | 250;

/**
 * * `cs-CZ` - Czech
 * * `en-US` - English
 */
export type DefaultLangEnum = 'cs-CZ' | 'en-US';

/**
 * * `dark` - Dark
 * * `light` - Light
 * * `system` - System
 */
export type DefaultThemeEnum = 'dark' | 'light' | 'system';

export type Experiment = {
    readonly id: string;
    readonly created: string;
    readonly modified: string;
    name?: string;
    start_time?: string | null;
    end_time?: string | null;
    note?: string;
    status?: ExperimentStatusEnum;
    onedata_file_id?: string | null;
    readonly created_by: number | null;
    readonly modified_by: number | null;
    dataset: string;
};

/**
 * * `new` - NEW
 * * `prepared` - PREPARED
 * * `running` - RUNNING
 * * `synchronizing` - SYNCHRONIZING
 * * `success` - SUCCESS
 * * `failure` - FAILURE
 * * `discarded` - DISCARDED
 */
export type ExperimentStatusEnum = 'new' | 'prepared' | 'running' | 'synchronizing' | 'success' | 'failure' | 'discarded';

export type Facility = {
    readonly id: string;
    readonly perms: string;
    readonly shares: string;
    readonly created: string;
    readonly modified: string;
    name: string;
    abbreviation: string;
    web?: string;
    email?: string;
    logo?: string;
    onedata_token?: string;
    onedata_provider_url?: string;
    readonly created_by: number | null;
    readonly modified_by: number | null;
};

export type FacilitySerializerMinimal = {
    readonly id: string;
    name: string;
    abbreviation: string;
    email?: string;
    web?: string;
    logo?: string;
};

export type Group = {
    name: string;
};

export type Instrument = {
    readonly id: string;
    name: string;
    support: string;
    contact: string;
    method: string;
    readonly facility: FacilitySerializerMinimal;
    default_data_dir?: string;
};

export type PaginatedDatasetResponseList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<DatasetResponse>;
};

export type PaginatedExperimentList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Experiment>;
};

export type PaginatedFacilityList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Facility>;
};

export type PaginatedGroupList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Group>;
};

export type PaginatedInstrumentList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Instrument>;
};

export type PaginatedProfileList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Profile>;
};

export type PaginatedProjectResponseList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<ProjectResponse>;
};

export type PaginatedSchemaList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<Schema>;
};

export type PaginatedUserList = {
    count?: number;
    next?: string | null;
    previous?: string | null;
    results?: Array<User>;
};

export type PatchedDataset = {
    readonly id?: string;
    readonly created?: string;
    readonly modified?: string;
    name?: string;
    description?: string;
    metadata?: unknown;
    onedata_file_id?: string | null;
    onedata_share_id?: string | null;
    onedata_dataset_id?: string | null;
    onedata_space_id?: string | null;
    doi?: string | null;
    reservationId?: string | null;
    status?: Status464Enum;
    readonly created_by?: number | null;
    readonly modified_by?: number | null;
    project?: string;
    shares?: SharesList;
    schema?: string | null;
    tags?: Array<(string)>;
};

export type PatchedExperiment = {
    readonly id?: string;
    readonly created?: string;
    readonly modified?: string;
    name?: string;
    start_time?: string | null;
    end_time?: string | null;
    note?: string;
    status?: ExperimentStatusEnum;
    onedata_file_id?: string | null;
    readonly created_by?: number | null;
    readonly modified_by?: number | null;
    dataset?: string;
};

export type PatchedFacility = {
    readonly id?: string;
    readonly perms?: string;
    readonly shares?: string;
    readonly created?: string;
    readonly modified?: string;
    name?: string;
    abbreviation?: string;
    web?: string;
    email?: string;
    logo?: string;
    onedata_token?: string;
    onedata_provider_url?: string;
    readonly created_by?: number | null;
    readonly modified_by?: number | null;
};

export type PatchedGroup = {
    name?: string;
};

export type PatchedInstrument = {
    readonly id?: string;
    name?: string;
    support?: string;
    contact?: string;
    method?: string;
    readonly facility?: FacilitySerializerMinimal;
    default_data_dir?: string;
};

export type PatchedProfile = {
    readonly created?: string;
    default_data_rows?: DefaultDataRowsEnum;
    readonly any_datasets?: string;
    readonly any_facilities?: string;
    readonly any_projects?: string;
    readonly app_version?: string;
    readonly avatar?: string;
    readonly last_login?: string;
    default_theme?: DefaultThemeEnum;
    default_lang?: DefaultLangEnum;
};

export type PatchedProject = {
    readonly id?: string;
    readonly created?: string;
    readonly modified?: string;
    name?: string;
    description?: string;
    onedata_space_id?: string;
    readonly created_by?: number | null;
    readonly modified_by?: number | null;
    facility?: string;
    shares?: SharesList;
    default_dataset_schema?: string | null;
};

export type PatchedSchema = {
    readonly id?: string;
    readonly created?: string;
    readonly modified?: string;
    version?: number;
    name?: string;
    description?: string | null;
    schema?: unknown;
    uischema?: unknown;
    readonly created_by?: number | null;
    readonly modified_by?: number | null;
};

export type PatchedUser = {
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    email?: string;
    /**
     * The groups this user belongs to. A user will get all permissions granted to each of their groups.
     */
    groups?: Array<(number)>;
    first_name?: string;
    last_name?: string;
    readonly name?: string;
};

export type Profile = {
    readonly created: string;
    default_data_rows?: DefaultDataRowsEnum;
    readonly any_datasets: string;
    readonly any_facilities: string;
    readonly any_projects: string;
    readonly app_version: string;
    readonly avatar: string;
    readonly last_login: string;
    default_theme?: DefaultThemeEnum;
    default_lang?: DefaultLangEnum;
};

export type Project = {
    readonly id: string;
    readonly created: string;
    readonly modified: string;
    name: string;
    description: string;
    onedata_space_id?: string;
    readonly created_by: number | null;
    readonly modified_by: number | null;
    facility: string;
    default_dataset_schema?: string | null;
};

export type ProjectResponse = {
    id: string;
    name: string;
    readonly created_by: UserSerializerMinimal;
    readonly perms: string;
    readonly shares: string;
    readonly facility: FacilitySerializerMinimal;
    readonly default_dataset_schema: BaseModel;
    readonly project_schema: BaseModel;
    readonly created: string;
    readonly modified: string;
    description: string;
    onedata_space_id?: string;
    modified_by?: number | null;
};

export type Reservation = {
    id: string;
    name: string;
    from_date: string;
    to_date: string;
    user: string;
    description: string;
    project_id: string;
    readonly dataset_status: string | null;
};

export type Schema = {
    readonly id: string;
    readonly created: string;
    readonly modified: string;
    version?: number;
    name: string;
    description?: string | null;
    schema?: unknown;
    uischema?: unknown;
    readonly created_by: number | null;
    readonly modified_by: number | null;
};

/**
 * * `new` - NEW
 * * `finished` - FINISHED
 */
export type Status464Enum = 'new' | 'finished';

export type User = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    email?: string;
    /**
     * The groups this user belongs to. A user will get all permissions granted to each of their groups.
     */
    groups?: Array<(number)>;
    first_name?: string;
    last_name?: string;
    readonly name: string;
};

export type UserSerializerMinimal = {
    readonly id: number;
    readonly full_name: string;
};

export type GetApiSchemaData = {
    format?: 'json' | 'yaml';
    lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
};

export type GetApiSchemaResponse = {
    [key: string]: unknown;
};

export type PostApiTokenLoginResponse = unknown;

export type PostApiTokenLogoutResponse = unknown;

export type PostApiTokenLogoutallResponse = unknown;

export type GetApiV1DatasetsData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
    /**
     * ID of the project to filter datasets by.
     */
    project?: string;
};

export type GetApiV1DatasetsResponse = PaginatedDatasetResponseList;

export type PostApiV1DatasetsData = {
    requestBody: Dataset;
};

export type PostApiV1DatasetsResponse = DatasetResponse;

export type GetApiV1DatasetsByIdData = {
    /**
     * A UUID string identifying this dataset.
     */
    id: string;
};

export type GetApiV1DatasetsByIdResponse = DatasetResponse;

export type PutApiV1DatasetsByIdData = {
    /**
     * A UUID string identifying this dataset.
     */
    id: string;
    requestBody: Dataset;
};

export type PutApiV1DatasetsByIdResponse = DatasetResponse;

export type PatchApiV1DatasetsByIdData = {
    /**
     * A UUID string identifying this dataset.
     */
    id: string;
    requestBody?: PatchedDataset;
};

export type PatchApiV1DatasetsByIdResponse = DatasetResponse;

export type DeleteApiV1DatasetsByIdData = {
    /**
     * A UUID string identifying this dataset.
     */
    id: string;
};

export type DeleteApiV1DatasetsByIdResponse = void;

export type GetApiV1DatasetsByIdGetByReservationIdData = {
    /**
     * A UUID string identifying this dataset.
     */
    id: string;
};

export type GetApiV1DatasetsByIdGetByReservationIdResponse = DatasetResponse;

export type PostApiV1DatasetsCreateDatasetData = {
    requestBody: Dataset;
};

export type PostApiV1DatasetsCreateDatasetResponse = DatasetResponse;

export type PostApiV1DatasetsCreateOnedataFolderData = {
    requestBody: Dataset;
};

export type PostApiV1DatasetsCreateOnedataFolderResponse = DatasetResponse;

export type PostApiV1DatasetsCreatePublicShareData = {
    requestBody: Dataset;
};

export type PostApiV1DatasetsCreatePublicShareResponse = DatasetResponse;

export type PostApiV1DatasetsShadowData = {
    requestBody: Dataset;
};

export type PostApiV1DatasetsShadowResponse = DatasetResponse;

export type GetApiV1ExperimentsData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1ExperimentsResponse = PaginatedExperimentList;

export type PostApiV1ExperimentsData = {
    requestBody: Experiment;
};

export type PostApiV1ExperimentsResponse = Experiment;

export type GetApiV1ExperimentsByIdData = {
    /**
     * A UUID string identifying this experiment.
     */
    id: string;
};

export type GetApiV1ExperimentsByIdResponse = Experiment;

export type PutApiV1ExperimentsByIdData = {
    /**
     * A UUID string identifying this experiment.
     */
    id: string;
    requestBody: Experiment;
};

export type PutApiV1ExperimentsByIdResponse = Experiment;

export type PatchApiV1ExperimentsByIdData = {
    /**
     * A UUID string identifying this experiment.
     */
    id: string;
    requestBody?: PatchedExperiment;
};

export type PatchApiV1ExperimentsByIdResponse = Experiment;

export type DeleteApiV1ExperimentsByIdData = {
    /**
     * A UUID string identifying this experiment.
     */
    id: string;
};

export type DeleteApiV1ExperimentsByIdResponse = void;

export type GetApiV1FacilitiesData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1FacilitiesResponse = PaginatedFacilityList;

export type PostApiV1FacilitiesData = {
    requestBody: Facility;
};

export type PostApiV1FacilitiesResponse = Facility;

export type GetApiV1FacilitiesByIdData = {
    /**
     * A UUID string identifying this facility.
     */
    id: string;
};

export type GetApiV1FacilitiesByIdResponse = Facility;

export type PutApiV1FacilitiesByIdData = {
    /**
     * A UUID string identifying this facility.
     */
    id: string;
    requestBody: Facility;
};

export type PutApiV1FacilitiesByIdResponse = Facility;

export type PatchApiV1FacilitiesByIdData = {
    /**
     * A UUID string identifying this facility.
     */
    id: string;
    requestBody?: PatchedFacility;
};

export type PatchApiV1FacilitiesByIdResponse = Facility;

export type DeleteApiV1FacilitiesByIdData = {
    /**
     * A UUID string identifying this facility.
     */
    id: string;
};

export type DeleteApiV1FacilitiesByIdResponse = void;

export type GetApiV1GroupsData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1GroupsResponse = PaginatedGroupList;

export type PostApiV1GroupsData = {
    requestBody: Group;
};

export type PostApiV1GroupsResponse = Group;

export type GetApiV1GroupsByIdData = {
    /**
     * A unique integer value identifying this group.
     */
    id: number;
};

export type GetApiV1GroupsByIdResponse = Group;

export type PutApiV1GroupsByIdData = {
    /**
     * A unique integer value identifying this group.
     */
    id: number;
    requestBody: Group;
};

export type PutApiV1GroupsByIdResponse = Group;

export type PatchApiV1GroupsByIdData = {
    /**
     * A unique integer value identifying this group.
     */
    id: number;
    requestBody?: PatchedGroup;
};

export type PatchApiV1GroupsByIdResponse = Group;

export type DeleteApiV1GroupsByIdData = {
    /**
     * A unique integer value identifying this group.
     */
    id: number;
};

export type DeleteApiV1GroupsByIdResponse = void;

export type GetApiV1InstrumentData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1InstrumentResponse = PaginatedInstrumentList;

export type PostApiV1InstrumentData = {
    requestBody: Instrument;
};

export type PostApiV1InstrumentResponse = Instrument;

export type GetApiV1InstrumentByIdData = {
    /**
     * A UUID string identifying this instrument.
     */
    id: string;
};

export type GetApiV1InstrumentByIdResponse = Instrument;

export type PutApiV1InstrumentByIdData = {
    /**
     * A UUID string identifying this instrument.
     */
    id: string;
    requestBody: Instrument;
};

export type PutApiV1InstrumentByIdResponse = Instrument;

export type PatchApiV1InstrumentByIdData = {
    /**
     * A UUID string identifying this instrument.
     */
    id: string;
    requestBody?: PatchedInstrument;
};

export type PatchApiV1InstrumentByIdResponse = Instrument;

export type DeleteApiV1InstrumentByIdData = {
    /**
     * A UUID string identifying this instrument.
     */
    id: string;
};

export type DeleteApiV1InstrumentByIdResponse = void;

export type GetApiV1InstrumentMetadataResponse = Instrument;

export type GetApiV1ProfileData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1ProfileResponse = PaginatedProfileList;

export type PostApiV1ProfileData = {
    requestBody?: Profile;
};

export type PostApiV1ProfileResponse = Profile;

export type GetApiV1ProfileByIdData = {
    /**
     * A UUID string identifying this user profile.
     */
    id: string;
};

export type GetApiV1ProfileByIdResponse = Profile;

export type PutApiV1ProfileByIdData = {
    /**
     * A UUID string identifying this user profile.
     */
    id: string;
    requestBody?: Profile;
};

export type PutApiV1ProfileByIdResponse = Profile;

export type PatchApiV1ProfileByIdData = {
    /**
     * A UUID string identifying this user profile.
     */
    id: string;
    requestBody?: PatchedProfile;
};

export type PatchApiV1ProfileByIdResponse = Profile;

export type DeleteApiV1ProfileByIdData = {
    /**
     * A UUID string identifying this user profile.
     */
    id: string;
};

export type DeleteApiV1ProfileByIdResponse = void;

export type GetApiV1ProjectsData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1ProjectsResponse = PaginatedProjectResponseList;

export type PostApiV1ProjectsData = {
    requestBody: Project;
};

export type PostApiV1ProjectsResponse = ProjectResponse;

export type GetApiV1ProjectsByIdData = {
    /**
     * A UUID string identifying this project.
     */
    id: string;
};

export type GetApiV1ProjectsByIdResponse = ProjectResponse;

export type PutApiV1ProjectsByIdData = {
    /**
     * A UUID string identifying this project.
     */
    id: string;
    requestBody: Project;
};

export type PutApiV1ProjectsByIdResponse = ProjectResponse;

export type PatchApiV1ProjectsByIdData = {
    /**
     * A UUID string identifying this project.
     */
    id: string;
    requestBody?: PatchedProject;
};

export type PatchApiV1ProjectsByIdResponse = ProjectResponse;

export type DeleteApiV1ProjectsByIdData = {
    /**
     * A UUID string identifying this project.
     */
    id: string;
};

export type DeleteApiV1ProjectsByIdResponse = void;

export type GetApiV1ReservationData = {
    /**
     * ISO formated FROM timestamp
     */
    dateFrom: string;
    /**
     * ISO formated TO timestamp
     */
    dateTo: string;
};

export type GetApiV1ReservationResponse = Array<Reservation>;

export type GetApiV1ReservationByIdData = {
    id: string;
};

export type GetApiV1ReservationByIdResponse = Reservation;

export type GetApiV1SchemasData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1SchemasResponse = PaginatedSchemaList;

export type PostApiV1SchemasData = {
    requestBody: Schema;
};

export type PostApiV1SchemasResponse = Schema;

export type GetApiV1SchemasByIdData = {
    /**
     * A UUID string identifying this schema.
     */
    id: string;
};

export type GetApiV1SchemasByIdResponse = Schema;

export type PutApiV1SchemasByIdData = {
    /**
     * A UUID string identifying this schema.
     */
    id: string;
    requestBody: Schema;
};

export type PutApiV1SchemasByIdResponse = Schema;

export type PatchApiV1SchemasByIdData = {
    /**
     * A UUID string identifying this schema.
     */
    id: string;
    requestBody?: PatchedSchema;
};

export type PatchApiV1SchemasByIdResponse = Schema;

export type DeleteApiV1SchemasByIdData = {
    /**
     * A UUID string identifying this schema.
     */
    id: string;
};

export type DeleteApiV1SchemasByIdResponse = void;

export type PostApiV1TempTokenByIdData = {
    id: string;
};

export type PostApiV1TempTokenByIdResponse = unknown;

export type GetApiV1UsersData = {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
};

export type GetApiV1UsersResponse = PaginatedUserList;

export type PostApiV1UsersData = {
    requestBody: User;
};

export type PostApiV1UsersResponse = User;

export type GetApiV1UsersByIdData = {
    /**
     * A unique integer value identifying this user.
     */
    id: number;
};

export type GetApiV1UsersByIdResponse = User;

export type PutApiV1UsersByIdData = {
    /**
     * A unique integer value identifying this user.
     */
    id: number;
    requestBody: User;
};

export type PutApiV1UsersByIdResponse = User;

export type PatchApiV1UsersByIdData = {
    /**
     * A unique integer value identifying this user.
     */
    id: number;
    requestBody?: PatchedUser;
};

export type PatchApiV1UsersByIdResponse = User;

export type DeleteApiV1UsersByIdData = {
    /**
     * A unique integer value identifying this user.
     */
    id: number;
};

export type DeleteApiV1UsersByIdResponse = void;

export type GetDataciteApiV1DoisResponse = unknown;

export type PostDataciteApiV1DoisResponse = unknown;

export type PutDataciteApiV1DoisResponse = unknown;

export type DeleteDataciteApiV1DoisResponse = void;

export type GetOnedataApiV1FilesResponse = unknown;

export type PostOnedataApiV1FilesResponse = unknown;

export type $OpenApiTs = {
    '/api/schema/': {
        get: {
            req: GetApiSchemaData;
            res: {
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/api/token/login/': {
        post: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
    };
    '/api/token/logout/': {
        post: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
    };
    '/api/token/logoutall/': {
        post: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
    };
    '/api/v1/datasets/': {
        get: {
            req: GetApiV1DatasetsData;
            res: {
                200: PaginatedDatasetResponseList;
            };
        };
        post: {
            req: PostApiV1DatasetsData;
            res: {
                201: DatasetResponse;
            };
        };
    };
    '/api/v1/datasets/{id}/': {
        get: {
            req: GetApiV1DatasetsByIdData;
            res: {
                200: DatasetResponse;
            };
        };
        put: {
            req: PutApiV1DatasetsByIdData;
            res: {
                200: DatasetResponse;
            };
        };
        patch: {
            req: PatchApiV1DatasetsByIdData;
            res: {
                200: DatasetResponse;
            };
        };
        delete: {
            req: DeleteApiV1DatasetsByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/datasets/{id}/get_by_reservation_id/': {
        get: {
            req: GetApiV1DatasetsByIdGetByReservationIdData;
            res: {
                200: DatasetResponse;
            };
        };
    };
    '/api/v1/datasets/create_dataset/': {
        post: {
            req: PostApiV1DatasetsCreateDatasetData;
            res: {
                200: DatasetResponse;
            };
        };
    };
    '/api/v1/datasets/create_onedata_folder/': {
        post: {
            req: PostApiV1DatasetsCreateOnedataFolderData;
            res: {
                200: DatasetResponse;
            };
        };
    };
    '/api/v1/datasets/create_public_share/': {
        post: {
            req: PostApiV1DatasetsCreatePublicShareData;
            res: {
                200: DatasetResponse;
            };
        };
    };
    '/api/v1/datasets/shadow/': {
        post: {
            req: PostApiV1DatasetsShadowData;
            res: {
                200: DatasetResponse;
            };
        };
    };
    '/api/v1/experiments/': {
        get: {
            req: GetApiV1ExperimentsData;
            res: {
                200: PaginatedExperimentList;
            };
        };
        post: {
            req: PostApiV1ExperimentsData;
            res: {
                201: Experiment;
            };
        };
    };
    '/api/v1/experiments/{id}/': {
        get: {
            req: GetApiV1ExperimentsByIdData;
            res: {
                200: Experiment;
            };
        };
        put: {
            req: PutApiV1ExperimentsByIdData;
            res: {
                200: Experiment;
            };
        };
        patch: {
            req: PatchApiV1ExperimentsByIdData;
            res: {
                200: Experiment;
            };
        };
        delete: {
            req: DeleteApiV1ExperimentsByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/facilities/': {
        get: {
            req: GetApiV1FacilitiesData;
            res: {
                200: PaginatedFacilityList;
            };
        };
        post: {
            req: PostApiV1FacilitiesData;
            res: {
                201: Facility;
            };
        };
    };
    '/api/v1/facilities/{id}/': {
        get: {
            req: GetApiV1FacilitiesByIdData;
            res: {
                200: Facility;
            };
        };
        put: {
            req: PutApiV1FacilitiesByIdData;
            res: {
                200: Facility;
            };
        };
        patch: {
            req: PatchApiV1FacilitiesByIdData;
            res: {
                200: Facility;
            };
        };
        delete: {
            req: DeleteApiV1FacilitiesByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/groups/': {
        get: {
            req: GetApiV1GroupsData;
            res: {
                200: PaginatedGroupList;
            };
        };
        post: {
            req: PostApiV1GroupsData;
            res: {
                201: Group;
            };
        };
    };
    '/api/v1/groups/{id}/': {
        get: {
            req: GetApiV1GroupsByIdData;
            res: {
                200: Group;
            };
        };
        put: {
            req: PutApiV1GroupsByIdData;
            res: {
                200: Group;
            };
        };
        patch: {
            req: PatchApiV1GroupsByIdData;
            res: {
                200: Group;
            };
        };
        delete: {
            req: DeleteApiV1GroupsByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/instrument/': {
        get: {
            req: GetApiV1InstrumentData;
            res: {
                200: PaginatedInstrumentList;
            };
        };
        post: {
            req: PostApiV1InstrumentData;
            res: {
                201: Instrument;
            };
        };
    };
    '/api/v1/instrument/{id}/': {
        get: {
            req: GetApiV1InstrumentByIdData;
            res: {
                200: Instrument;
            };
        };
        put: {
            req: PutApiV1InstrumentByIdData;
            res: {
                200: Instrument;
            };
        };
        patch: {
            req: PatchApiV1InstrumentByIdData;
            res: {
                200: Instrument;
            };
        };
        delete: {
            req: DeleteApiV1InstrumentByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/instrument/metadata/': {
        get: {
            res: {
                200: Instrument;
            };
        };
    };
    '/api/v1/profile/': {
        get: {
            req: GetApiV1ProfileData;
            res: {
                200: PaginatedProfileList;
            };
        };
        post: {
            req: PostApiV1ProfileData;
            res: {
                201: Profile;
            };
        };
    };
    '/api/v1/profile/{id}/': {
        get: {
            req: GetApiV1ProfileByIdData;
            res: {
                200: Profile;
            };
        };
        put: {
            req: PutApiV1ProfileByIdData;
            res: {
                200: Profile;
            };
        };
        patch: {
            req: PatchApiV1ProfileByIdData;
            res: {
                200: Profile;
            };
        };
        delete: {
            req: DeleteApiV1ProfileByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/projects/': {
        get: {
            req: GetApiV1ProjectsData;
            res: {
                200: PaginatedProjectResponseList;
            };
        };
        post: {
            req: PostApiV1ProjectsData;
            res: {
                201: ProjectResponse;
            };
        };
    };
    '/api/v1/projects/{id}/': {
        get: {
            req: GetApiV1ProjectsByIdData;
            res: {
                200: ProjectResponse;
            };
        };
        put: {
            req: PutApiV1ProjectsByIdData;
            res: {
                200: ProjectResponse;
            };
        };
        patch: {
            req: PatchApiV1ProjectsByIdData;
            res: {
                200: ProjectResponse;
            };
        };
        delete: {
            req: DeleteApiV1ProjectsByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/reservation/': {
        get: {
            req: GetApiV1ReservationData;
            res: {
                /**
                 * Created. New resource in response
                 */
                200: Array<Reservation>;
            };
        };
    };
    '/api/v1/reservation/{id}/': {
        get: {
            req: GetApiV1ReservationByIdData;
            res: {
                /**
                 * Reservation details
                 */
                200: Reservation;
                /**
                 * Reservation not found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/schemas/': {
        get: {
            req: GetApiV1SchemasData;
            res: {
                200: PaginatedSchemaList;
            };
        };
        post: {
            req: PostApiV1SchemasData;
            res: {
                201: Schema;
            };
        };
    };
    '/api/v1/schemas/{id}/': {
        get: {
            req: GetApiV1SchemasByIdData;
            res: {
                200: Schema;
            };
        };
        put: {
            req: PutApiV1SchemasByIdData;
            res: {
                200: Schema;
            };
        };
        patch: {
            req: PatchApiV1SchemasByIdData;
            res: {
                200: Schema;
            };
        };
        delete: {
            req: DeleteApiV1SchemasByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/api/v1/temp-token/{id}/': {
        post: {
            req: PostApiV1TempTokenByIdData;
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
    };
    '/api/v1/users/': {
        get: {
            req: GetApiV1UsersData;
            res: {
                200: PaginatedUserList;
            };
        };
        post: {
            req: PostApiV1UsersData;
            res: {
                201: User;
            };
        };
    };
    '/api/v1/users/{id}/': {
        get: {
            req: GetApiV1UsersByIdData;
            res: {
                200: User;
            };
        };
        put: {
            req: PutApiV1UsersByIdData;
            res: {
                200: User;
            };
        };
        patch: {
            req: PatchApiV1UsersByIdData;
            res: {
                200: User;
            };
        };
        delete: {
            req: DeleteApiV1UsersByIdData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/datacite-api/v1/dois/': {
        get: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
        post: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
        put: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
        delete: {
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
    '/onedata-api/v1/files/': {
        get: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
        post: {
            res: {
                /**
                 * No response body
                 */
                200: unknown;
            };
        };
    };
};